### PR TITLE
Add Debian package support

### PR DESCRIPTION
**Pull request by philippmeisberger**
Simplify the installation process under Debian based systems by using a Debian package.

### CODE REVIEW

**Comment by philippmeisberger** [comment]
What do you think about my request @grazzolini ?

**Comment by ge-fa** [comment]
`debian/` shouldn't be placed within the upstream repo, aka here. Also, there is a [RFP bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792380) filled in Debian, so please take the "official way" and get this into Debian.

**Comment by philippmeisberger** [comment]
It's a common practice to have a `debian` directory in the repo. This project is great IMHO and I just wanted to simplify the installation on Debian based systems. There is only one command to build the package (dpkg-buildpackage -uc -us) and another one to install it (`dpkg-i chkboot*.deb`) using the package manager. Clean and simple ;)

**Comment by grazzolini** [comment]
@philippmeisberger, I have started working on this project again. I have to agree with @ge-fa here, we cannot include debian specifics into the repository.  For example, I use this project mainly on Arch Linux, and ever since I inherited the package there, I have kept the packaging separate from the actual content.

**Pull request closed without merging**
