### PR TITLE
Detect vfat boot partition and ignore inode

### PR DESCRIPTION
**Pull request by lyknode**

### CODE REVIEW

**Comment by the-sane** [comment]
A vfat file system doesn't support extents either.  It doesn't seem to break hash comparisons like the inodes do, but `$blcks` can be left out as well as `$inode`.

**Comment by lyknode** [comment]
`$blcks` removed.

**Review by grazzolini — CHANGES_REQUESTED** [review]
If I understood this correctly, the idea is to try and detect where the ESP is mounted and hash it as well, alongside /boot. The issue is, searching by vfat filesystem is not consistent, specially if you have more than one ESP, on more than one disk for example, or if you actually have a vfat filesystem for something else.

My recommended way of handling with this has been to have the boot partition mounted to /boot (or have it be a directory under /) and mount the esp to /boot/efi. This way chkboot hashes everything that is needed without the need to know if this is a EFI setup or not.

If you can come up with a reliable way to find the ESP partition that is being used (in case you have more than one), I would be happy to merge the change. Consider the case where both ESP's are being mounted through fstab, for example. You need to detect which one is being used for your current boot loader and hash it.

I have an Arch Linux specific mkinitcpio hook, chkcryptoboot, that does that. But it is explicitly told where the EFI stub is and also is ran on early userspace, rather than running on the actual system.

**Comment by lyknode** [comment]
Hi @grazzolini,

First of all, thanks for taking the time to review this PR.

> If I understood this correctly, the idea is to try and detect where the ESP is mounted and hash it as well, alongside /boot. The issue is, searching by vfat filesystem is not consistent, specially if you have more than one ESP, on more than one disk for example, or if you actually have a vfat filesystem for something else.

Not quite, this patch aim to detect any vfat filesystem mounted under `/boot`. Note that here, it should actually check under `$BOOTDIR` and not `/boot`, I'll correct that.
If so, it will disable `$blcks` and `$inode` in the output.
This check is run **only** under the `/boot` so having more than one ESP would not conflict with it.
 
> My recommended way of handling with this has been to have the boot partition mounted to /boot (or have it be a directory under /) and mount the esp to /boot/efi. This way chkboot hashes everything that is needed without the need to know if this is a EFI setup or not.

This works but it will omit the ESP files. It might be desirable to include those files as well.

I have currently three devices with three different layout:
- One booting with an MBR (no changes here, `$blcks` and `$inodes` are computed)
- One booting with an `/boot` ext4 partition and the ESP mounted as `/boot/efi` as Arch wiki suggest it (chkboot works but `$blcks` and `$inodes` are disabled all together)
- One booting with [EFISTUB](https://wiki.archlinux.org/index.php/EFISTUB). It is just a ESP `/boot` partition containing the kernel and the initramfs, Nothing else. In that case chkboot works as well by omiting only  `$blcks` and `$inodes`.

Each of those layout works with this PR.

> If you can come up with a reliable way to find the ESP partition that is being used (in case you have more than one), I would be happy to merge the change. Consider the case where both ESP's are being mounted through fstab, for example. You need to detect which one is being used for your current boot loader and hash it.

This is already done as only filesystem under `$BOOTDIR` (again `/boot` must be removed from the patch) are checked.

> I have an Arch Linux specific mkinitcpio hook, chkcryptoboot, that does that. But it is explicitly told where the EFI stub is and also is ran on early userspace, rather than running on the actual system.

This patch was never designed to specifically check for other ESP, not mounted under the `$BOOTDIR`, it was more to make it work when ESP is present under it.

**Review by grazzolini — COMMENTED** [review]
This iteration is an improvement, but I'm considering dropping $inode and $blcks altogether, since we can rely solely on the hash to detect changes. Also, since we use plain diff to check for differences, this won't have any impact at all.

I'm still reticent about the way things are being ran though. You can probably use findmnt for cleaner results. I'm testing your changes as you make them.

**Comment by lyknode** [comment]
> This iteration is an improvement, but I'm considering dropping $inode and $blcks altogether, since we can rely solely on the hash to detect changes. Also, since we use plain diff to check for differences, this won't have any impact at all.

That would solve the compatibility problem with filesystem that do not support `$inode` and `$blcks`. I agree with you on that, relying on the checksum should suffice.

> I'm still reticent about the way things are being ran though. You can probably use findmnt for cleaner results. I'm testing your changes as you make them.

Let me know if you want to proceed with removing those two. If not, I'll gladly make the change to use `findmnt`.

**Comment by grazzolini** [comment]
> That would solve the compatibility problem with filesystem that do not support `$inode` and `$blcks`. I agree with you on that, relying on the checksum should suffice.
 
I understand the rationale for having them on the original chkboot submission. But, since we rely on a strong hashing algorithm already, I don't think those are needed. It is safe to remove those.

> Let me know if you want to proceed with removing those two. If not, I'll gladly make the change to use `findmnt`.

Using findmnt is better than using /proc and cleaner too, since you can query only for the information you need. I will need to probably change the PKGBUILD of chkboot on Arch Linux though, even though util-linux is probably present on all installations.

Can you make these changes on this PR?

**Comment by lyknode** [comment]
`$inode` and `$blcks` removed.

Should we bump the hash to `sha512` ?

**Comment by grazzolini** [comment]
Yes. Arch Linux has since moved away from 32-bit and sha512 is usually faster on 64-bit, so I'm don't see a reason to keep the hash as sha256.

**Comment by lyknode** [comment]
This now looks ok to me.
If you want, I can rebase/squash those first three commits so we have a cleaner history.

Let me know what you think of it.

**Comment by grazzolini** [comment]
Please rebase from master so we can have everything into a single commit. It is now harder to track changes.

**Review by grazzolini — APPROVED** [review]

**Pull request merged**
